export const projectData = {
  recorderKarate: {
    title: "Recorder Karate",
    image: "/recorderKarate.png",
    link: "https://recorderkarate.netlify.app",
    info: "Recorder Karate was built for the Elliot Elementary school music classroom. The students use the application to progress through a series of songs to earn their belts. Recorder Karate was built using React and React Router.",
    tech: "HTML, CSS, JavaScript, React",
    date: "November 2022",
    repo: "https://github.com/patricksperanza/recorder-karate-v2",
  },
  frontEndFlashcards: {
    title: "Front End Flashcards",
    image: "/frontEndFlashcards.png",
    link: "https://front-endflashcards.netlify.app/",
    info: "Front End Flashcards is a full stack study application built with the MERN stack. The app allows users to create, edit, and delete flashcards to study for interview questions.",
    tech: "HTML, CSS, JavaScript, React, Node, Express, MongoDB",
    date: "March 2023",
    repo: "https://github.com/patricksperanza/mern-flashcards-front-end, https://github.com/patricksperanza/mern-flashcards-server",
  },
  playfulPiano: {
    title: "Playful Piano",
    image: "/playfulPiano.png",
    link: "https://playfulpiano.netlify.app/",
    info: "Playful Piano is an interactive React application that is designed to help young children learn simple songs on the piano. The piano can be played by click or by using the keyboard.",
    tech: "HTML, CSS, JavaScript, React",
    date: "February 2023",
    repo: "https://github.com/patricksperanza/playful-piano",
  },
  gameHub: {
    title: "Game Hub",
    image: "/gameHub.png",
    link: "https://game-hub-lovat.vercel.app/",
    info: "Game Hub is a clone of the Rawg.io website built with TypeScript and React. This website was built by following Mosh Hamedi's new React and TypeScript course.",
    tech: "HTML, CSS, TypeScript, React",
    date: "March 2023",
    repo: "https://github.com/patricksperanza/game-hub",
  },
}
